analyzer:
#   exclude:
#     - path/to/excluded/files/**
include: package:pedantic/analysis_options.yaml

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
# linter:
  # rules:
    # - some rule