name: extended_math
description: Library that add functionality of all maths sections that don't exist in dart:math. 
version: 0.0.10
homepage: https://github.com/YevhenKap/extended_math
author: Kapelianovych Yevhen <kapelianovych.y.v@gmail.com>
license: MIT

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  quiver: ^2.0.1

dev_dependencies:
