name: extended_math
description: Library that add functionality of all maths sections that don't exist in dart:math.
version: 0.0.30
homepage: https://github.com/YevhenKap/extended_math
license: MIT

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  meta: ^1.9.0
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.20.0
  lints: ^2.0.0
