name: extended_math
description: Library that add functionality of all maths sections that don't exist in dart:math.
version: 0.0.29+1
homepage: https://github.com/YevhenKap/extended_math
license: MIT

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
