name: extended_math
description: Library that add functionality of all maths sections that don't exist in dart:math.
version: 0.1.0
homepage: https://github.com/YevhenKap/extended_math
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.20.0
  lints: ^2.0.0
